### ISSUE TITLE
 No such file or directory

### ISSUE THREAD

**Issue by yukkon** [ahoward/lockfile#5]
Errno::ENOENT: No such file or directory - ~/processor_lockfiles/.ws-tukalskiy_11723_rails_1376555657_345799_839901143.lck
    from /home/alex/.rvm/rubies/ruby-2.0.0-head/lib/ruby/2.0.0/open-uri.rb:36:in `initialize'
    from /home/alex/.rvm/rubies/ruby-2.0.0-head/lib/ruby/2.0.0/open-uri.rb:36:in`open'
    from /home/alex/.rvm/rubies/ruby-2.0.0-head/lib/ruby/2.0.0/open-uri.rb:36:in `open'
    from /home/alex/.rvm/gems/ruby-2.0.0-head/gems/lockfile-2.1.0/lib/lockfile.rb:484:in`create'
    from /home/alex/.rvm/gems/ruby-2.0.0-head/gems/lockfile-2.1.0/lib/lockfile.rb:422:in `create_tmplock'
    from /home/alex/.rvm/gems/ruby-2.0.0-head/gems/lockfile-2.1.0/lib/lockfile.rb:204:in`block in lock'
    from /home/alex/.rvm/gems/ruby-2.0.0-head/gems/lockfile-2.1.0/lib/lockfile.rb:517:in `block (2 levels) in attempt'
    from /home/alex/.rvm/gems/ruby-2.0.0-head/gems/lockfile-2.1.0/lib/lockfile.rb:517:in`catch'
    from /home/alex/.rvm/gems/ruby-2.0.0-head/gems/lockfile-2.1.0/lib/lockfile.rb:517:in `block in attempt'
    from /home/alex/.rvm/gems/ruby-2.0.0-head/gems/lockfile-2.1.0/lib/lockfile.rb:517:in`loop'
    from /home/alex/.rvm/gems/ruby-2.0.0-head/gems/lockfile-2.1.0/lib/lockfile.rb:517:in `attempt'
    from /home/alex/.rvm/gems/ruby-2.0.0-head/gems/lockfile-2.1.0/lib/lockfile.rb:201:in`lock'
    from /home/alex/.rvm/gems/ruby-2.0.0-head/gems/lockfile-2.1.0/lib/lockfile.rb:191:in `initialize'
    from /home/alex/dev/benefits/lib/workers/base_processor.rb:23:in`new'
    from /home/alex/dev/benefits/lib/workers/base_processor.rb:23:in `process_queue'

**Comment by yukkon** [comment]
sorry i'm stupid
